services:
  otel-lgtm:
    container_name: otel-lgtm
    image: grafana/otel-lgtm
    ports:
      - "8888:3000"  # Grafana UI
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    networks:
      - app-network
    volumes:
      - ./otel-lgtm-data:/data
  nginx:
    image: nginx:latest
    container_name: nginx
    platform: linux/amd64
    volumes:
      - ./source:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "5318:5318"
    networks:
      - app-network
    depends_on:
      - fpm
  fpm:
    container_name: fpm
    build:
      context: .
      dockerfile: ./dockerfiles/php-otel/Dockerfile
    platform: linux/amd64
    volumes:
      - ./source/laravel:/var/www/html
    environment:
      OTEL_PHP_AUTOLOAD_ENABLED: true
      OTEL_SERVICE_NAME: backend
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-lgtm:4318
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-lgtm:4318/v1/traces
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-lgtm:4318/v1/logs
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-lgtm:4318/v1/metrics
      OTEL_PROPAGATORS: baggage,tracecontext
    networks:
      - app-network
  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: ./dockerfiles/php-otel/Dockerfile
    platform: linux/amd64
    volumes:
      - ./source/laravel:/app
    working_dir: /app
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: funticket
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/mmrm-app-api/data:/var/lib/mysql
      - ./mysql/mmrm-app-api/logs:/var/log/mysql
    networks:
      - app-network
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge